#!/usr/bin/env bash
# Display a list of currently running
# Shows all processes, for all users, including those which might not have a TTY.
ps -A --no-headers -o pid,user,group,comm,args | sed 's/^ *//'
